// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc9nRw_16L5TAHB8zNq9OLpOIfvpA_iwI',
    appId: '1:550058539961:android:a61409a9220bb995445468',
    messagingSenderId: '550058539961',
    projectId: 'golog-f6c2a',
    storageBucket: 'golog-f6c2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOgEDQ3eqEl5t79i6aExSWkZf9G5PyT3M',
    appId: '1:550058539961:ios:20e993fcfbd40e37445468',
    messagingSenderId: '550058539961',
    projectId: 'golog-f6c2a',
    storageBucket: 'golog-f6c2a.appspot.com',
    androidClientId: '550058539961-9mjq08r0eo5gj73orlhrdol0jon78v1e.apps.googleusercontent.com',
    iosClientId: '550058539961-0if9s6nghje16bir3ck9cmjfi8t5fv31.apps.googleusercontent.com',
    iosBundleId: 'com.example.tracker',
  );
}
